openai_api_key: "ab-proj-dkdjkdjsklejelkhkehejhe"
google_project: "fun-project-123456-g0"
google_location: "us-central1"
google_api_key: "AIbabasisnotarealkey"
dryad_api_key: "NotARealDryadApiKey1234567890"
dryad_secret: "NotARealDryadSecretKey0987654321"
user_agent: "MyApp/1.0 (mailto:myemail@example.com)"